server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
<<<<<<< HEAD

=======
>>>>>>> ae88f71a5d98cf993b2fdaf0d6538975fc5d4348
  data:
    redis:
      host: localhost
      port: 6379
  web:
    resources:
      static-locations:
        - classpath:/static/ # 애플리케이션의 resources/static 디렉토리에서 정적 자원을 찾습니다.

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/shallwe_db?serverTimeZone=Asia/Seoul #데이터 베이스 연결을 위한 URL을 설정 합니다.
    driver-class-name: com.mysql.cj.jdbc.Driver #드라이버 클래스를 설정 합니다.
    username: root #사용자 ID를 지정
    password: asd123 #DB 비밀번호 여기서는 빈 문자열로 설정
  sql:
    init:
      schema-locations:
        - classpath:db/table.sql
      data-locations:
        - classpath:db/data.sql
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
<<<<<<< HEAD
    username: # 이메일 인증 용 gmail 정보 
    password: # 이메일 인증 용 mail api pw 정보 
=======
    username: secondclover714@gmail.com
    password: pawf rjzd mnwd ptsq
>>>>>>> ae88f71a5d98cf993b2fdaf0d6538975fc5d4348
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.3

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.apache.ibatis: DEBUG

file:
  upload-dir: C:\\work_spring\\upload/

tenco:
<<<<<<< HEAD
  key: 07f5efbd3004db57fcd53846050461b203e984faa9d957285aa26f8b

# 소셜 로그인 관련 정보  
googleClientId:
  key: # 구글 클라이언트 아이디
    
googleClientSecret:
  key: # 구글 클라이언트 시크릿

kakaoClientId:
  key: # 카카오 클라이언트 아이디

naverClientId:
  key: # 네이버 클라이언트 아이디
    
naverClientSecret:
  key: # 네이버 클라이언트 시크릿 

  
  
=======
  key: 07f5efbd3004db57fcd53846050461b203e984faa9d957285aa26f8b
>>>>>>> ae88f71a5d98cf993b2fdaf0d6538975fc5d4348
