server:
  port: 8080
  servlet:
    encoding:
<<<<<<< HEAD
      charset: utf-8
      force: true

spring:
  data:
    redis:
      host: localhost
      port: 6379

=======
      charset: utf-8 #서블릿의 응답과 요청 인코딩을 UTF-8로 설정 
      force: true #요청과 응답에 대해 이 인코딩을 강제로 사용하도록 설정합니다. 

spring:
  web:
    resources:
      static-locations:
        - classpath:/static/ # 애플리케이션의 resources/static 디렉토리에서 정적 자원을 찾습니다.
>>>>>>> lee2
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/shallwe_db?serverTimeZone=Asia/Seoul #데이터 베이스 연결을 위한 URL을 설정합니다.
    driver-class-name: com.mysql.cj.jdbc.Driver #드라이버 클래스를 설정합니다.
    username: root #사용자 ID를 지정
    password: asd123 #DB 비밀번호 
  sql:
    init:
      schema-locations:
        - classpath:db/table.sql
      data-locations:
<<<<<<< HEAD
        - classpath:db/data.sql
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: secondclover714@gmail.com
    password: pawf rjzd mnwd ptsq
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.3

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
=======
      - classpath:db/data.sql 
      
  h2:
    console:
      enabled: true #H2 데이터 베이스 콘솔을 활성화합니다. 

  output:
    ansi:
      enabled: always #콘솔 출력에 ANSI 색상 코드를 사용할 수 있도록 설정 

# mybatis 설정
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml #MyBatis 매퍼 파일 위치를 설정합니다.
  configuration:
    map-underscore-to-camel-case: true #데이터베이스의 언더스코어 네이밍(column_name)을 카멜 케이스(columnName)로 자동 매핑합니다.
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #SQL 로깅 구현체를 설정합니다. 
>>>>>>> lee2

logging:
  level:
    org.apache.ibatis: DEBUG

<<<<<<< HEAD
=======
# 초기 파라미터 설정
>>>>>>> lee2
file:
  upload-dir: C:\\work_spring\\upload/

tenco:
  key: 07f5efbd3004db57fcd53846050461b203e984faa9d957285aa26f8b
<<<<<<< HEAD
=======

# 정적 자원 폴더 설정

>>>>>>> lee2
